### ISSUE TITLE
Doyo Guitar Hero Controller not working all the way

### ISSUE THREAD

**Issue by Orangy-Man** [raphaelgoulart/ya_inputdisplay#16]
Hello. I have the Doyo Guitar Hero Controller (shitty, i know) and whenever i use this, it detects the first 4 frets but they are not in order. It wont even detect the last fret at all.

**Comment by Orangy-Man** [comment]
incase you do some research on the guitar, yes i know its keyboard inputs by default (the controller) but ive gotten it to work as a normal ps3 guitar hero controller and thats how i tested it with this app

**Comment by raphaelgoulart** [comment]
Try remapping the bindings, by clicking the buttons in the input display itself, then pressing the desired fret. This should fix that - let me know if it does (or doesn't)

**Comment by Orangy-Man** [comment]
> Try remapping the bindings, by clicking the buttons in the input display itself, then pressing the desired fret. This should fix that - let me know if it does (or doesn't)

i just got told this somewhere else also. im dumb lol. thank you for the help
