### ISSUE TITLE
Keyboard input not detected when not focused.

### ISSUE THREAD

**Issue by kioskt11** [raphaelgoulart/ya_inputdisplay#3]
When I'm focused on the app the keyboard inputs work, but when it's unfocused it does not work.

**Comment by raphaelgoulart** [comment]
Not possible with Godot's native input system. I plan to rewrite using win32api for input on a separate thread to make it FPS independent, that might make it work but it'll take a while

**Comment by kioskt11** [comment]
Okay, thank you!
