### ISSUE TITLE
Various Issuses (Rock Band 1 Wii Stratocaster)

### ISSUE THREAD

**Issue by 21stCenturyGuy08** [raphaelgoulart/ya_inputdisplay#4]
The program doesn't seem to work all that well with a Wii Stratocaster. Some inputs seem to not want to show up sometimes and the orange input seems to be mapped to the Start Button rather than the orange button. [https://drive.google.com/file/d/1vguiPhSJhPz5uz0G38THeRUvTpC4dSQw/view?usp=drive_link](url)

**Comment by raphaelgoulart** [comment]
It looks like you just need to remap the buttons - click on top of the button in the input viewer, then press the desired fret/strum direction to bind it that button.

Please let me know if that works

**Comment by 21stCenturyGuy08** [comment]
Okay that worked. I didn't know that was a feature. My apologies.
