### ISSUE TITLE
Possible Linux build?

### ISSUE THREAD

**Issue by ColetteDiskette** [raphaelgoulart/ya_inputdisplay#5]
I'm currently trying to diagnose some issues I'm having while playing YARG, and being able to use this would be immensely helpful. (It could also be nice for me to be able to use for streams.) I'm curious how feasible a Linux build would be. (I tried to build it myself, but even trying to follow the Godot documentation, I ran into issues.)

Thanks!

**Comment by raphaelgoulart** [comment]
Hello! I just created an export preset for Linux/X11, downloaded its export template, and had a go, but I don't have a Linux environment to test this at all, so let me know if this works:
https://drive.google.com/file/d/1ZL0RIse1Iba2xILU0nGoQ_8ITiZCKeyd/view?usp=sharing

If it does, I'll add it to the Releases tab (possibly with a binary for 0.0.3 as well, incase axis support bugs out for anyone)

**Comment by ColetteDiskette** [comment]
It works, however it has a transparent background for me using either my Plasma X11 or Wayland session.

**Comment by raphaelgoulart** [comment]
It's the same on Windows as well, for OBS transparency, not a bug
