### ISSUE TITLE
How to setup this?

### ISSUE THREAD

**Issue by gozfrt** [raphaelgoulart/ya_inputdisplay#6]
I use Santroller guitar but the software thinks green and red are strum inputs and select/start are blue and orange

**Comment by raphaelgoulart** [comment]
You need to remap buttons, apparently -- click on top of the button you wish to remap in the viewer (i.e. green fret), and press the corresponding button on your guitar. Do it for each fret. It should auto-save when closing the program.

Let me know if it works!

**Comment by gozfrt** [comment]
that does indeed work haha. Wouldnt be a bad idea to include that on the readme file 😉
How do you unmap a button now since my strum is green and red

**Comment by raphaelgoulart** [comment]
It is included on the readme file, under Controls, but I can consider making it a bit more obvious (i.e. under its own help topic).

It's not possible to unmap buttons at this moment. Ideally, you'd just bind your strum up/down as well, like you did with the frets. If that's not possible for you, let me know and I'll try to figure out some makeshift solution.

**Comment by gozfrt** [comment]
oh apparently it is, I read the whole thing more than couple of times but didn't see it lol
well damn

**Comment by raphaelgoulart** [comment]
I'm not home so I can't test this solution, but try opening ```%APPDATA%\Godot\app_userdata\ya_inputdisplay\yaid_settings.cfg``` in any text editing tool, and changing the ```gp_btn``` variable in sections ```[5]``` and ```[6]``` to something like 999 (so it maps those to buttons that don't exist), and let me know if it works.

Otherwise, I can try some things in a couple hours

**Comment by gozfrt** [comment]
yep, that fixed it. Thanks 👍

**Comment by gozfrt** [comment]
Edit: 

It did for 1 time. Now it does the exact same thing. Forces strum up and down to green and red. Every exit it overwrites the same gpbuttons to down and up as in green and red, no matter what numbers I put there or if the cfg is in only read mode
