### ISSUE TITLE
Files in .gotdot/editor are modified while using the editor (could these be added to the gitignore?)

### ISSUE THREAD

**Issue by SkyJumper409x** [raphaelgoulart/ya_inputdisplay#7]
i `git clone`d this repo as one does, and, upon opening the project with Godot engine, noticed I suddenly had 16 changes. 
This was due to some files in `.godot/editor/` being modified to adjust to the fact that i am using Linux (Arch Linux, to be specific) and some editor related cache being created, aswell as some folders in `.godot/shader_cache/` being created.
This is what causes the additional changes.

I would recommend adding `.godot/editor` and `.godot/shader_cache` to the `.gitignore` file and removing those two folders from the repo so the changes in the .gitignore have an effect.

I have already done those changes in a fork (https://github.com/SkyJumper409x/ya_inputdisplay_gitignore_fix) but i have decided to not open a pr yet as i am unsure as to if this might be an unwelcome change.

**Comment by raphaelgoulart** [comment]
Feel free to open the PR! Those are certainly welcome changes, I just never really set the time aside to do it.

Thank you!
