### ISSUE TITLE
Binding a Xbox360 Les Paul's downstrum or upstrum to any button causes double/duplicate inputs

### ISSUE THREAD

**Issue by SkyJumper409x** [raphaelgoulart/ya_inputdisplay#9]
i recorded short videos of me performing the bug:
[First Video](https://github.com/raphaelgoulart/ya_inputdisplay/assets/136763949/a18a0787-5253-446f-8869-c88c3c26a288)
[Second Video](https://github.com/raphaelgoulart/ya_inputdisplay/assets/136763949/3318a309-b659-43c5-ac8b-7e1741f5c567)

I am not sure if this is related to Linux, but i doubt that since clone hero and yarg are working just fine. it also isnt a hardware issue, i tested for that. It might be related to LPs specifically but i am not sure. 
This does not negatively impact the usage of the program significantly, it is just kinda annoying because the inputs per second are doubled too.

I use arch linux with sddm and kde plasma, my controller is connected to my pc with a second-hand microsoft wireless adapter. I recentlty soldered new strumswitches but didnt use the program prior to that.

**Comment by raphaelgoulart** [comment]
My guess is the program is receiving the strum input as both an axis _and_ a button. Try using the [0.0.3](https://github.com/raphaelgoulart/ya_inputdisplay/releases/tag/0.0.3) version, which doesn't have axis support.

**Comment by SkyJumper409x** [comment]
> My guess is the program is receiving the strum input as both an axis _and_ a button. Try using the [0.0.3](https://github.com/raphaelgoulart/ya_inputdisplay/releases/tag/0.0.3) version, which doesn't have axis support.

ah, i forgot to post my findings here.
no, that is not the case, albeit it being the first thing i checked for.
there are appeaently just two button indexes that get fired (i placed a bunch of print() method), and the check for a gamepad button being pressed just gets fired twice. the axis code is unrelated.
 i do not know what that second button index is in godot. most websites i find display 13 & 20 for downstrum but godot seems to be indexing the buttons differently. 
 the annoying part is i cannot map the second button index in the project settings to find out, because the first button index has priority for some reason.

**Comment by SkyJumper409x** [comment]
i am working on a fix for this, but it will not work if the fps are uncapped.

**Comment by SkyJumper409x** [comment]
...ignore that, i figured it out.
will open pr once i removed all the debug junk i used
